[[installation_prerequisites]]
= Installation Prerequisites

Verify that the following prerequisites have been met before installing the {product-name}.

== Software

* Java Platform, JRE version 8+
* {ProductShortName} is tested on Linux, Windows, and macOS. Other operating systems with Java 8+ support should work equally well.

NOTE: If you are running macOS, it is recommended to set the maximum number of user processes, `maxproc`, to at least `4096`, and the maximum number of open files, `maxfiles`, to `100000`.

== Hardware

The following memory and disk space requirements are the minimum needed to run {ProductShortName}. If your application is very large or you need to evaluate multiple applications, you may want to increase these values to improve performance.

ifndef::cli-guide[]
For tips on how to optimize performance, see the link:{ProductDocUserGuideURL}#optimize_performance[Optimize {ProductShortName} Performance] section of the {ProductShortName} _{UserCLIBookName}_.
endif::cli-guide[]

ifdef::cli-guide[]
For tips on how to optimize performance, see xref:optimize_performance[Optimize {ProductShortName} Performance].
endif::cli-guide[]

* A minimum of 4 GB RAM. For better performance, a quad-core processor with 8 GB RAM is recommended. This allows 3 - 4 GB RAM for use by the JVM.
* A minimum of 4 GB of free disk space. A fast disk, especially a solid-state drive (SSD), should improve performance.
